(function(){
  'use strict';
  var STORAGE_KEY='coach_2048_v1';
  var LOCALES=['en','ko','zh','hi','ru','ja','es','pt','id','tr','de','fr'];
  var EN={
    pageTitle:'2048 Board Analyzer: Find Your Best Next Move | DopaBrain',pageDescription:'Enter any 2048 board and compare all legal moves with a transparent browser-local analysis.',
    skip:'Skip to board editor',play:'Play 2048',language:'Language',eyebrow:'2048 POSITION LAB · NO SIGN-UP',title:'2048 Board Analyzer',lead:'Enter the tiles you see. The coach simulates every legal direction, previews the board before a random tile appears, and explains the strongest next move.',
    chipRules:'Exact merge rules',chipMoves:'Four-move comparison',chipLocal:'Runs locally',chipLookahead:'One-step lookahead',limitTitle:'A coach, not an oracle',limitBody:'The next tile appears randomly, so the result is a transparent heuristic—not a guaranteed perfect move. Your tile values stay in this browser and are never included in analytics.',
    step1:'STEP 1 · ENTER BOARD',boardTitle:'Your current 4×4 board',clear:'Clear',boardHelp:'Use 0 for an empty cell. Valid tiles are powers of two from 2 to 131072.',pastePlaceholder:'Paste 16 values separated by spaces or commas',apply:'Apply',presets:'Try a position',presetOpening:'Open board',presetCorner:'Corner chain',presetTrap:'Merge trap',presetEndgame:'Crowded board',analyze:'Analyze all four moves',
    emptyTitle:'Your next move starts here',emptyBody:'Load a sample or enter your board, then compare every legal direction.',step2:'STEP 2 · COMPARE MOVES',recommendation:'RECOMMENDED NEXT MOVE',moveTableTitle:'Move comparison',previewTitle:'Board after selected move',beforeRandom:'Before the random tile',whyTitle:'Why this move?',copy:'Copy analysis',playPosition:'Play 2048 now',ad:'Advertisement',
    methodKicker:'TRANSPARENT SCORING',methodTitle:'What the coach measures',factorEmpty:'Empty cells',factorEmptyBody:'More space usually gives future tiles and merges room to move.',factorMerge:'Merge value',factorMergeBody:'Immediate points and remaining adjacent pairs reward useful consolidation.',factorCorner:'Corner control',factorCornerBody:'Keeping the largest tile in a corner supports a stable edge chain.',factorOrder:'Tile order',factorOrderBody:'Smooth, monotonic rows and columns are easier to combine than scattered peaks.',methodNote:'For lookahead, the coach tries a 2 or 4 in every empty cell using the usual 90%/10% weighting, then evaluates the best legal reply. It does not search the full game tree.',
    playCard:'Play 2048',playCardBody:'Test the idea on the live board',guideCard:'2048 strategy guide',guideCardBody:'Learn corner chains and board control',gamesCard:'More brain games',gamesCardBody:'Browse puzzles and quick challenges',tools:'← All tools',footer:'Independent helper for the open-source 2048 game concept.',
    up:'Up',right:'Right',down:'Down',left:'Left',illegal:'No change',points:'merge points',empty:'empty',pairs:'pairs',corner:'corner',maxTile:'Max tile',legalMoves:'Legal moves',bestScore:'Board score',analysisCount:'Analyses',clearLead:'Clear advantage',smallLead:'Small advantage',closeCall:'Close call—inspect both previews',gameOver:'No legal moves remain',invalid:'Enter only 0 or powers of two from 2 to 131072.',pasteInvalid:'Paste exactly 16 valid values.',applied:'Board applied',cleared:'Board cleared',copied:'Analysis copied',copyFailed:'Could not copy analysis',reasonSpace:'Keeps {n} empty cells available.',reasonPoints:'Creates {n} immediate merge points.',reasonCorner:'Keeps the largest tile anchored in a corner.',reasonPairs:'Leaves {n} adjacent merge opportunities.',reasonLookahead:'Has the strongest expected reply after the next random tile.',reasonOnly:'It is the only legal move.',reportTitle:'2048 board analysis',recommended:'Recommended',previewed:'Previewed'
  };
  var KO={pageTitle:'2048 보드 분석기: 최선의 다음 수 찾기 | DopaBrain',pageDescription:'2048 보드를 입력하고 모든 가능한 이동을 브라우저에서 비교하세요.',skip:'보드 편집기로 이동',play:'2048 플레이',language:'언어',eyebrow:'2048 포지션 연구소 · 가입 불필요',title:'2048 보드 분석 코치',lead:'현재 타일을 입력하세요. 코치가 네 방향을 실제 규칙으로 시뮬레이션하고 새 타일이 생기기 전 보드와 추천 이유를 보여줍니다.',chipRules:'정확한 합치기 규칙',chipMoves:'네 방향 비교',chipLocal:'기기 안에서 계산',chipLookahead:'한 단계 예측',limitTitle:'보조 도구이지 정답 예언은 아닙니다',limitBody:'다음 타일은 무작위로 생기므로 결과는 설명 가능한 휴리스틱이며 완벽한 수를 보장하지 않습니다. 타일 값은 분석 데이터로 전송되지 않습니다.',step1:'1단계 · 보드 입력',boardTitle:'현재 4×4 보드',clear:'비우기',boardHelp:'빈칸은 0입니다. 2부터 131072까지 2의 거듭제곱만 입력할 수 있습니다.',pastePlaceholder:'공백이나 쉼표로 구분한 값 16개 붙여넣기',apply:'적용',presets:'예제 포지션',presetOpening:'초반 보드',presetCorner:'코너 체인',presetTrap:'합치기 함정',presetEndgame:'빽빽한 보드',analyze:'네 방향 모두 분석',emptyTitle:'다음 수를 분석해보세요',emptyBody:'예제를 불러오거나 현재 보드를 입력한 뒤 가능한 방향을 비교하세요.',step2:'2단계 · 이동 비교',recommendation:'추천하는 다음 이동',moveTableTitle:'이동 비교',previewTitle:'선택한 이동 후 보드',beforeRandom:'새 타일 생성 전',whyTitle:'이 이동을 고른 이유',copy:'분석 복사',playPosition:'지금 2048 플레이',ad:'광고',methodKicker:'투명한 평가 기준',methodTitle:'코치가 측정하는 것',factorEmpty:'빈칸',factorEmptyBody:'공간이 많으면 다음 타일과 합치기를 움직일 여유가 생깁니다.',factorMerge:'합치기 가치',factorMergeBody:'즉시 점수와 남은 인접 쌍을 함께 평가합니다.',factorCorner:'코너 유지',factorCornerBody:'가장 큰 타일을 코너에 두면 안정적인 가장자리 체인을 만들기 쉽습니다.',factorOrder:'타일 순서',factorOrderBody:'부드럽고 단조로운 행과 열이 흩어진 봉우리보다 합치기 쉽습니다.',methodNote:'한 단계 예측은 모든 빈칸에 2와 4가 90%/10%로 생기는 경우를 시험하고 최선의 다음 응답을 평가합니다. 전체 게임 트리를 탐색하지는 않습니다.',playCard:'2048 플레이',playCardBody:'실제 보드에서 아이디어 확인',guideCard:'2048 전략 가이드',guideCardBody:'코너 체인과 보드 제어 학습',gamesCard:'다른 두뇌 게임',gamesCardBody:'퍼즐과 짧은 도전 둘러보기',tools:'← 모든 도구',footer:'오픈소스 2048 게임 개념을 위한 독립 보조 도구.',up:'위',right:'오른쪽',down:'아래',left:'왼쪽',illegal:'변화 없음',points:'합치기 점수',empty:'빈칸',pairs:'합칠 쌍',corner:'코너',maxTile:'최대 타일',legalMoves:'가능한 이동',bestScore:'보드 점수',analysisCount:'분석 횟수',clearLead:'뚜렷한 우위',smallLead:'근소한 우위',closeCall:'비슷한 결과—두 미리보기를 비교하세요',gameOver:'가능한 이동이 없습니다',invalid:'0 또는 2부터 131072까지 2의 거듭제곱만 입력하세요.',pasteInvalid:'유효한 값 16개를 붙여넣으세요.',applied:'보드를 적용했습니다',cleared:'보드를 비웠습니다',copied:'분석을 복사했습니다',copyFailed:'분석을 복사하지 못했습니다',reasonSpace:'빈칸 {n}개를 유지합니다.',reasonPoints:'즉시 합치기 점수 {n}점을 만듭니다.',reasonCorner:'가장 큰 타일을 코너에 유지합니다.',reasonPairs:'인접한 합치기 기회 {n}개를 남깁니다.',reasonLookahead:'다음 무작위 타일 이후 기대 응답이 가장 좋습니다.',reasonOnly:'유일하게 가능한 이동입니다.',reportTitle:'2048 보드 분석',recommended:'추천',previewed:'미리보기'};
  var ZH={pageTitle:'2048 棋盘分析器：找到最佳下一步 | DopaBrain',pageDescription:'输入任意 2048 棋盘，在浏览器中比较所有合法移动。',skip:'跳到棋盘编辑器',play:'玩 2048',language:'语言',eyebrow:'2048 局面实验室 · 无需注册',title:'2048 棋盘分析器',lead:'输入当前方块。工具会按真实规则模拟四个方向，预览随机方块出现前的棋盘，并解释推荐的下一步。',chipRules:'准确合并规则',chipMoves:'四方向比较',chipLocal:'本地运行',chipLookahead:'一步前瞻',limitTitle:'辅助判断，而非绝对答案',limitBody:'下一块方块随机出现，因此结果是透明的启发式建议，并不保证全局最优。方块数值不会发送到分析服务。',step1:'第 1 步 · 输入棋盘',boardTitle:'当前 4×4 棋盘',clear:'清空',boardHelp:'空格填 0。有效方块为 2 到 131072 的 2 次幂。',pastePlaceholder:'粘贴 16 个以空格或逗号分隔的数字',apply:'应用',presets:'尝试局面',presetOpening:'开局',presetCorner:'角落链',presetTrap:'合并陷阱',presetEndgame:'拥挤棋盘',analyze:'分析四个方向',emptyTitle:'从下一步开始',emptyBody:'载入示例或输入棋盘，然后比较所有合法方向。',step2:'第 2 步 · 比较移动',recommendation:'推荐下一步',moveTableTitle:'移动比较',previewTitle:'所选移动后的棋盘',beforeRandom:'随机方块出现前',whyTitle:'为什么推荐这一步？',copy:'复制分析',playPosition:'立即玩 2048',ad:'广告',methodKicker:'透明评分',methodTitle:'分析器衡量什么',factorEmpty:'空格数量',factorEmptyBody:'更多空间通常能为新方块和后续合并留出余地。',factorMerge:'合并价值',factorMergeBody:'同时奖励即时得分和移动后仍相邻的相同方块。',factorCorner:'角落控制',factorCornerBody:'把最大方块留在角落有利于稳定的边缘序列。',factorOrder:'方块顺序',factorOrderBody:'平滑且单调的行列比散乱峰值更容易合并。',methodNote:'前瞻会在每个空格尝试以 90%/10% 概率出现的 2 或 4，再评估最佳合法回应；它不会搜索整棵游戏树。',playCard:'玩 2048',playCardBody:'在真实棋盘上验证建议',guideCard:'2048 策略指南',guideCardBody:'学习角落链和棋盘控制',gamesCard:'更多益智游戏',gamesCardBody:'浏览拼图和快速挑战',tools:'← 所有工具',footer:'面向开源 2048 游戏概念的独立辅助工具。',up:'上',right:'右',down:'下',left:'左',illegal:'无变化',points:'合并得分',empty:'空格',pairs:'可合并对',corner:'角落',maxTile:'最大方块',legalMoves:'合法移动',bestScore:'棋盘评分',analysisCount:'分析次数',clearLead:'优势明显',smallLead:'略占优势',closeCall:'结果接近，请比较两个预览',gameOver:'没有合法移动',invalid:'只可输入 0 或 2 到 131072 的 2 次幂。',pasteInvalid:'请粘贴恰好 16 个有效数字。',applied:'棋盘已应用',cleared:'棋盘已清空',copied:'分析已复制',copyFailed:'无法复制分析',reasonSpace:'保留 {n} 个空格。',reasonPoints:'立即获得 {n} 合并分。',reasonCorner:'最大方块仍固定在角落。',reasonPairs:'保留 {n} 个相邻合并机会。',reasonLookahead:'随机方块出现后的预期回应最强。',reasonOnly:'这是唯一合法的移动。',reportTitle:'2048 棋盘分析',recommended:'推荐',previewed:'预览'};
  var JA={pageTitle:'2048盤面解析：次の最善手を探す | DopaBrain',pageDescription:'2048の盤面を入力し、合法な4方向をブラウザ内で比較します。',title:'2048 盤面分析コーチ',lead:'現在のタイルを入力すると、4方向を実際のルールでシミュレーションし、ランダムタイルが出る前の盤面と推奨理由を表示します。',play:'2048をプレイ',language:'言語',step1:'ステップ1 · 盤面入力',boardTitle:'現在の4×4盤面',clear:'クリア',analyze:'4方向を分析',recommendation:'おすすめの次の一手',up:'上',right:'右',down:'下',left:'左',illegal:'変化なし',empty:'空き',points:'合体得点',pairs:'合体候補',corner:'角',maxTile:'最大タイル',legalMoves:'合法手',bestScore:'盤面評価',analysisCount:'分析回数',clearLead:'明確な優位',smallLead:'わずかに優位',closeCall:'僅差—両方のプレビューを確認',gameOver:'合法手がありません',invalid:'0または2～131072の2の累乗を入力してください。',pasteInvalid:'有効な値を16個貼り付けてください。',reasonSpace:'空きマスを{n}個確保します。',reasonPoints:'すぐに{n}点を獲得します。',reasonCorner:'最大タイルを角に維持します。',reasonPairs:'隣接する合体候補を{n}組残します。',reasonLookahead:'次のランダムタイル後の期待応答が最良です。',reasonOnly:'唯一の合法手です。'};
  var PT={pageTitle:'Analisador de tabuleiro 2048: melhor próxima jogada | DopaBrain',title:'Analisador de tabuleiro 2048',lead:'Digite as peças atuais para simular as quatro direções e comparar a próxima jogada.',play:'Jogar 2048',language:'Idioma',up:'Cima',right:'Direita',down:'Baixo',left:'Esquerda',illegal:'Sem mudança',empty:'vazias',points:'pontos de fusão',pairs:'pares',corner:'canto',maxTile:'Maior peça',legalMoves:'Jogadas válidas',bestScore:'Pontuação do tabuleiro',analysisCount:'Análises',clearLead:'Vantagem clara',smallLead:'Pequena vantagem',closeCall:'Resultado próximo—compare as prévias',gameOver:'Não restam jogadas válidas'};
  var FR={pageTitle:'Analyseur de grille 2048 : meilleur prochain coup | DopaBrain',title:'Analyseur de grille 2048',lead:'Saisissez les tuiles actuelles pour simuler les quatre directions et comparer le prochain coup.',play:'Jouer à 2048',language:'Langue',up:'Haut',right:'Droite',down:'Bas',left:'Gauche',illegal:'Aucun changement',empty:'vides',points:'points de fusion',pairs:'paires',corner:'coin',maxTile:'Tuile max.',legalMoves:'Coups valides',bestScore:'Score du plateau',analysisCount:'Analyses',clearLead:'Avantage net',smallLead:'Petit avantage',closeCall:'Résultats proches—comparez les aperçus',gameOver:'Aucun coup valide'};
  var OVERLAYS={ko:KO,zh:ZH,ja:JA,pt:PT,fr:FR,es:{pageTitle:'Analizador de tablero 2048: mejor próximo movimiento | DopaBrain',title:'Analizador de tablero 2048',play:'Jugar 2048',language:'Idioma',up:'Arriba',right:'Derecha',down:'Abajo',left:'Izquierda',illegal:'Sin cambio',empty:'vacías',points:'puntos de fusión',pairs:'pares',corner:'esquina'},de:{pageTitle:'2048-Brettanalyse: Finde deinen besten nächsten Zug | DopaBrain',title:'2048-Brettanalyse',play:'2048 spielen',language:'Sprache',up:'Oben',right:'Rechts',down:'Unten',left:'Links',illegal:'Keine Änderung',empty:'frei',points:'Fusionspunkte',pairs:'Paare',corner:'Ecke'},ru:{pageTitle:'Анализатор доски 2048: лучший следующий ход | DopaBrain',title:'Анализатор доски 2048',play:'Играть в 2048',language:'Язык',up:'Вверх',right:'Вправо',down:'Вниз',left:'Влево',illegal:'Без изменений'},hi:{pageTitle:'2048 बोर्ड विश्लेषक: अगली सर्वश्रेष्ठ चाल | DopaBrain',title:'2048 बोर्ड विश्लेषक',play:'2048 खेलें',language:'भाषा',up:'ऊपर',right:'दायाँ',down:'नीचे',left:'बायाँ'},id:{pageTitle:'Penganalisis papan 2048: langkah terbaik berikutnya | DopaBrain',title:'Penganalisis papan 2048',play:'Main 2048',language:'Bahasa',up:'Atas',right:'Kanan',down:'Bawah',left:'Kiri'},tr:{pageTitle:'2048 tahta analizörü: en iyi sonraki hamle | DopaBrain',title:'2048 Tahta Analizörü',play:'2048 oyna',language:'Dil',up:'Yukarı',right:'Sağ',down:'Aşağı',left:'Sol'}};
  var params=new URLSearchParams(location.search),stored='';try{stored=localStorage.getItem('app_language')||''}catch(e){}
  var browser=(navigator.language||'en').toLowerCase().split('-')[0];
  var locale=LOCALES.indexOf(params.get('lang'))>=0?params.get('lang'):(LOCALES.indexOf(stored)>=0?stored:(LOCALES.indexOf(browser)>=0?browser:'en'));
  var copy=Object.assign({},EN,OVERLAYS[locale]||{});
  var DIRS=['up','right','down','left'],ARROWS={up:'↑',right:'→',down:'↓',left:'←'};
  var PRESETS={opening:[[0,0,0,0],[0,2,0,0],[0,4,2,0],[16,8,4,2]],corner:[[0,2,4,8],[0,4,8,16],[2,8,16,32],[256,128,64,32]],trap:[[4,2,4,2],[8,4,8,4],[16,8,16,8],[64,32,32,16]],endgame:[[1024,512,256,128],[32,64,128,64],[16,32,64,32],[8,4,2,0]]};
  var inputs=[],analysis=null,selectedDirection=null,session=loadSession();
  var els={language:document.getElementById('language'),board:document.getElementById('boardInputs'),error:document.getElementById('inputError'),empty:document.getElementById('resultEmpty'),content:document.getElementById('resultContent'),moveList:document.getElementById('moveList'),preview:document.getElementById('previewBoard'),reasons:document.getElementById('reasons'),toast:document.getElementById('toast')};
  function loadSession(){try{return Object.assign({board:null,count:0},JSON.parse(localStorage.getItem(STORAGE_KEY)||'{}'))}catch(e){return{board:null,count:0}}}
  function saveSession(board){session.board=board;try{localStorage.setItem(STORAGE_KEY,JSON.stringify(session))}catch(e){}}
  function track(name,data){if(typeof window.gtag!=='function')return;var source=params.get('source')||'';if(!/^[a-z0-9_]{1,40}$/i.test(source))source='direct';window.gtag('event',name,Object.assign({event_category:'engagement',source_app:'coach_2048',surface_name:'coach_2048',content_locale:locale,entry_source:source,revenue_goal:'daily_0_10'},data||{}))}
  function toast(message){els.toast.textContent=message;els.toast.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(function(){els.toast.classList.remove('show')},2100)}
  function cellLevel(value){return value?Math.min(17,Math.round(Math.log2(value))):0}
  function paintCell(el,value){el.dataset.level=String(cellLevel(value));if(el.tagName!=='INPUT')el.textContent=value||''}
  function makeBoardInputs(){for(var i=0;i<16;i++){var input=document.createElement('input');input.className='board-cell';input.type='text';input.inputMode='numeric';input.maxLength=6;input.setAttribute('aria-label','Row '+(Math.floor(i/4)+1)+', column '+(i%4+1));input.addEventListener('input',function(){this.value=this.value.replace(/[^0-9]/g,'');paintCell(this,Number(this.value)||0);this.classList.remove('invalid')});inputs.push(input);els.board.appendChild(input)}}
  function boardFromInputs(){var invalid=false,values=inputs.map(function(input){var raw=input.value.trim(),value=raw===''?0:Number(raw);var ok=isValidValue(value);input.classList.toggle('invalid',!ok);if(!ok)invalid=true;return value});if(invalid){showError(copy.invalid);return null}hideError();return chunk(values)}
  function chunk(values){return[values.slice(0,4),values.slice(4,8),values.slice(8,12),values.slice(12,16)]}
  function isValidValue(value){return Number.isInteger(value)&&value>=0&&value<=131072&&(value===0||(value&(value-1))===0)}
  function isValidBoard(board){return Array.isArray(board)&&board.length===4&&board.every(function(row){return Array.isArray(row)&&row.length===4&&row.every(isValidValue)})}
  function setBoard(board){board.flat().forEach(function(value,i){inputs[i].value=value?String(value):'';paintCell(inputs[i],value);inputs[i].classList.remove('invalid')});saveSession(board)}
  function clone(board){return board.map(function(row){return row.slice()})}
  function same(a,b){return a.every(function(row,r){return row.every(function(value,c){return value===b[r][c]})})}
  function mergeLine(line){var compact=line.filter(Boolean),result=[],score=0,merges=0;for(var i=0;i<compact.length;i++){if(i+1<compact.length&&compact[i]===compact[i+1]){var value=compact[i]*2;result.push(value);score+=value;merges++;i++}else result.push(compact[i])}while(result.length<4)result.push(0);return{line:result,score:score,merges:merges}}
  function transpose(board){return board[0].map(function(_,c){return board.map(function(row){return row[c]})})}
  function simulate(board,direction){var working=clone(board),vertical=direction==='up'||direction==='down',reverse=direction==='right'||direction==='down';if(vertical)working=transpose(working);var score=0,merges=0;working=working.map(function(row){var line=reverse?row.slice().reverse():row.slice(),result=mergeLine(line);score+=result.score;merges+=result.merges;return reverse?result.line.reverse():result.line});if(vertical)working=transpose(working);return{direction:direction,board:working,valid:!same(board,working),score:score,merges:merges}}
  function emptyCells(board){var cells=[];board.forEach(function(row,r){row.forEach(function(value,c){if(!value)cells.push([r,c])})});return cells}
  function maxTile(board){return Math.max.apply(null,board.flat())}
  function mergePairs(board){var pairs=0;for(var r=0;r<4;r++)for(var c=0;c<4;c++){if(!board[r][c])continue;if(c<3&&board[r][c]===board[r][c+1])pairs++;if(r<3&&board[r][c]===board[r+1][c])pairs++}return pairs}
  function smoothness(board){var score=0;for(var r=0;r<4;r++)for(var c=0;c<4;c++){if(!board[r][c])continue;var value=Math.log2(board[r][c]);if(c<3&&board[r][c+1])score-=Math.abs(value-Math.log2(board[r][c+1]));if(r<3&&board[r+1][c])score-=Math.abs(value-Math.log2(board[r+1][c]))}return score}
  function monotonicity(board){function penalty(line){var inc=0,dec=0;for(var i=0;i<3;i++){var a=line[i]?Math.log2(line[i]):0,b=line[i+1]?Math.log2(line[i+1]):0;if(a>b)inc+=a-b;else dec+=b-a}return-Math.min(inc,dec)}var total=0;board.forEach(function(row){total+=penalty(row)});transpose(board).forEach(function(row){total+=penalty(row)});return total}
  function snakeScore(board){var patterns=[[0,1,2,3,7,6,5,4,8,9,10,11,15,14,13,12],[3,2,1,0,4,5,6,7,11,10,9,8,12,13,14,15],[12,13,14,15,11,10,9,8,4,5,6,7,3,2,1,0],[15,14,13,12,8,9,10,11,7,6,5,4,0,1,2,3]],flat=board.flat();return Math.max.apply(null,patterns.map(function(pattern){return pattern.reduce(function(sum,index,position){return sum+(flat[index]?Math.log2(flat[index]):0)*(16-position)},0)}))}
  function metrics(board){var empty=emptyCells(board).length,max=maxTile(board),corners=[board[0][0],board[0][3],board[3][0],board[3][3]];return{empty:empty,max:max,corner:max>0&&corners.indexOf(max)>=0?1:0,pairs:mergePairs(board),smooth:smoothness(board),mono:monotonicity(board),snake:snakeScore(board)}}
  function evaluate(board){var m=metrics(board),maxLog=m.max?Math.log2(m.max):0;return m.empty*280+m.pairs*95+m.corner*maxLog*190+m.smooth*15+m.mono*32+m.snake*2}
  function expectedReply(board){var cells=emptyCells(board);if(!cells.length)return evaluate(board);var total=0;cells.forEach(function(cell){[[2,.9],[4,.1]].forEach(function(option){var spawned=clone(board);spawned[cell[0]][cell[1]]=option[0];var replies=DIRS.map(function(direction){return simulate(spawned,direction)}).filter(function(move){return move.valid});var best=replies.length?Math.max.apply(null,replies.map(function(move){return evaluate(move.board)+move.score*7})):evaluate(spawned);total+=option[1]*best/cells.length})});return total}
  function analyzeBoard(board){var current=metrics(board),moves=DIRS.map(function(direction){var move=simulate(board,direction);move.metrics=metrics(move.board);move.rating=move.valid?move.score*8+expectedReply(move.board):-Infinity;return move}).sort(function(a,b){return b.rating-a.rating});var legal=moves.filter(function(move){return move.valid});return{board:board,current:current,moves:moves,legal:legal,best:legal[0]||null}}
  function format(template,n){return template.replace('{n}',String(n))}
  function confidenceText(result){if(!result.best)return copy.gameOver;if(result.legal.length===1)return copy.reasonOnly;var gap=result.legal[0].rating-result.legal[1].rating,base=Math.max(1,Math.abs(result.legal[0].rating));var ratio=gap/base;return ratio>.12?copy.clearLead:(ratio>.035?copy.smallLead:copy.closeCall)}
  function reasonsFor(result,move){if(!move)return[];var reasons=[];if(result.legal.length===1)reasons.push(copy.reasonOnly);if(move.metrics.empty>=result.current.empty)reasons.push(format(copy.reasonSpace,move.metrics.empty));if(move.score>0)reasons.push(format(copy.reasonPoints,move.score));if(move.metrics.corner)reasons.push(copy.reasonCorner);if(move.metrics.pairs>0)reasons.push(format(copy.reasonPairs,move.metrics.pairs));reasons.push(copy.reasonLookahead);return reasons.slice(0,4)}
  function renderBoard(container,board){container.replaceChildren();board.flat().forEach(function(value){var el=document.createElement('div');el.className='board-cell';el.dataset.level=String(cellLevel(value));el.textContent=value||'';container.appendChild(el)})}
  function metricCard(value,label){var el=document.createElement('div'),strong=document.createElement('strong'),span=document.createElement('span');strong.textContent=String(value);span.textContent=label;el.append(strong,span);return el}
  function renderAnalysis(result,selected){analysis=result;selectedDirection=selected||(result.best&&result.best.direction);els.empty.hidden=true;els.content.hidden=false;var best=result.best;document.getElementById('bestArrow').textContent=best?ARROWS[best.direction]:'×';document.getElementById('bestMove').textContent=best?copy[best.direction]:copy.gameOver;document.getElementById('confidence').textContent=confidenceText(result);var diagnostics=document.getElementById('diagnostics');diagnostics.replaceChildren();diagnostics.append(metricCard(result.current.max,copy.maxTile),metricCard(result.current.empty,copy.empty),metricCard(result.legal.length,copy.legalMoves),metricCard(session.count,copy.analysisCount));els.moveList.replaceChildren();result.moves.forEach(function(move){var row=document.createElement('button');row.type='button';row.className='move-row'+(move.direction===selectedDirection?' selected':'')+(best&&move.direction===best.direction?' recommended':'');row.dataset.direction=move.direction;row.disabled=!move.valid;var arrow=document.createElement('span'),body=document.createElement('span'),strong=document.createElement('strong'),small=document.createElement('small'),rating=document.createElement('b');arrow.textContent=ARROWS[move.direction];strong.textContent=copy[move.direction];small.textContent=move.valid?(move.score+' '+copy.points+' · '+move.metrics.empty+' '+copy.empty+' · '+move.metrics.pairs+' '+copy.pairs):copy.illegal;rating.textContent=move.valid?String(Math.round(move.rating)): '—';body.append(strong,small);row.append(arrow,body,rating);els.moveList.appendChild(row)});renderSelected(result,selectedDirection)}
  function renderSelected(result,direction){var move=result.moves.find(function(item){return item.direction===direction&&item.valid})||result.best;if(!move)return;selectedDirection=move.direction;els.moveList.querySelectorAll('.move-row').forEach(function(row){row.classList.toggle('selected',row.dataset.direction===selectedDirection)});renderBoard(els.preview,move.board);els.reasons.replaceChildren();reasonsFor(result,move).forEach(function(reason){var li=document.createElement('li');li.textContent=reason;els.reasons.appendChild(li)})}
  function performAnalysis(userTriggered){var board=boardFromInputs();if(!board)return;var started=performance.now(),result=analyzeBoard(board);session.count+=userTriggered?1:0;saveSession(board);renderAnalysis(result);if(userTriggered)track('coach_2048_analyze',{legal_move_count:result.legal.length,empty_cell_count:result.current.empty,max_tile:result.current.max,max_in_corner:result.current.corner,analysis_count:session.count,recommended_direction:result.best?result.best.direction:'none',calculation_ms:Math.round(performance.now()-started)})}
  function showError(message){els.error.textContent=message;els.error.hidden=false}function hideError(){els.error.hidden=true;els.error.textContent=''}
  function applyLocale(){copy=Object.assign({},EN,OVERLAYS[locale]||{});document.documentElement.lang=locale;document.title=copy.pageTitle;var meta=document.querySelector('meta[name=description]');if(meta)meta.content=copy.pageDescription;document.querySelectorAll('[data-i18n]').forEach(function(el){if(copy[el.dataset.i18n])el.textContent=copy[el.dataset.i18n]});document.querySelectorAll('[data-i18n-placeholder]').forEach(function(el){if(copy[el.dataset.i18nPlaceholder])el.placeholder=copy[el.dataset.i18nPlaceholder]});els.language.value=locale;var canonical='https://dopabrain.com/puzzle-2048/coach.html'+(locale==='en'?'':'?lang='+locale);document.querySelector('link[rel=canonical]').href=canonical;document.querySelector('meta[property="og:url"]').content=canonical;document.querySelector('meta[property="og:title"]').content=copy.title;document.querySelectorAll('[data-preserve-lang]').forEach(function(link){var url=new URL(link.href,location.href);url.searchParams.set('lang',locale);link.href=url.pathname+url.search});var guides={zh:'/portal/blog/zh/2048-strategy-guide.html',ja:'/portal/blog/ja/2048-puzzle-strategy-guide.html',pt:'/portal/blog/pt/2048-estrategia-guia.html',fr:'/portal/blog/fr/guide-strategie-2048.html',es:'/portal/blog/es/2048-estrategia-guia.html',id:'/portal/blog/id/strategi-game-2048.html',tr:'/portal/blog/tr/2048-oyun-stratejisi.html',de:'/portal/blog/de/2048-puzzle-strategie.html'};document.getElementById('guideLink').href=guides[locale]||'/portal/blog/en/number-puzzle-2048-tips.html';if(analysis)renderAnalysis(analysis,selectedDirection)}
  function copyReport(){if(!analysis||!analysis.best)return;var move=analysis.moves.find(function(item){return item.direction===selectedDirection})||analysis.best;var report=[copy.reportTitle,copy.recommended+': '+ARROWS[analysis.best.direction]+' '+copy[analysis.best.direction],copy.previewed+': '+copy[move.direction],copy.maxTile+': '+analysis.current.max,copy.empty+': '+analysis.current.empty,'',reasonsFor(analysis,move).map(function(reason){return'• '+reason}).join('\n'),'https://dopabrain.com/puzzle-2048/coach.html'].join('\n');var promise=navigator.clipboard&&navigator.clipboard.writeText?navigator.clipboard.writeText(report):Promise.reject();promise.then(function(){toast(copy.copied)}).catch(function(){var area=document.createElement('textarea');area.value=report;area.style.position='fixed';area.style.opacity='0';document.body.appendChild(area);area.select();try{document.execCommand('copy');toast(copy.copied)}catch(e){toast(copy.copyFailed)}area.remove()});track('coach_2048_copy',{recommended_direction:analysis.best.direction,preview_direction:move.direction})}
  makeBoardInputs();
  setBoard(isValidBoard(session.board)?session.board:PRESETS.corner);applyLocale();performAnalysis(false);
  document.getElementById('analyze').addEventListener('click',function(){performAnalysis(true)});
  document.getElementById('clearBoard').addEventListener('click',function(){setBoard(PRESETS.opening.map(function(row){return row.map(function(){return 0})}));analysis=null;els.content.hidden=true;els.empty.hidden=false;toast(copy.cleared);track('coach_2048_clear')});
  document.getElementById('presets').addEventListener('click',function(event){var button=event.target.closest('[data-preset]');if(!button)return;setBoard(PRESETS[button.dataset.preset]);performAnalysis(false);toast(copy.applied);track('coach_2048_preset_select',{preset_name:button.dataset.preset,empty_cell_count:metrics(PRESETS[button.dataset.preset]).empty})});
  document.getElementById('applyPaste').addEventListener('click',function(){var values=document.getElementById('pasteBoard').value.trim().split(/[\s,;|]+/).filter(Boolean).map(Number);if(values.length!==16||values.some(function(value){return!isValidValue(value)})){showError(copy.pasteInvalid);return}hideError();var board=chunk(values);setBoard(board);performAnalysis(false);toast(copy.applied);track('coach_2048_board_paste',{empty_cell_count:metrics(board).empty,max_tile:metrics(board).max})});
  els.moveList.addEventListener('click',function(event){var row=event.target.closest('.move-row');if(!row||row.disabled||!analysis)return;renderSelected(analysis,row.dataset.direction);track('coach_2048_move_preview',{preview_direction:row.dataset.direction,is_recommended:analysis.best&&row.dataset.direction===analysis.best.direction})});
  document.getElementById('copyAnalysis').addEventListener('click',copyReport);
  els.language.addEventListener('change',function(){locale=LOCALES.indexOf(els.language.value)>=0?els.language.value:'en';try{localStorage.setItem('app_language',locale)}catch(e){}var url=new URL(location.href);url.searchParams.set('lang',locale);history.replaceState({},'',url.pathname+url.search);applyLocale();track('coach_2048_language_change',{selected_locale:locale})});
  document.querySelectorAll('[data-destination]').forEach(function(link){link.addEventListener('click',function(){var eventName=link.dataset.destination==='play'?'coach_2048_play_click':(link.dataset.destination==='guide'?'coach_2048_guide_click':'coach_2048_related_click');track(eventName,{destination_type:link.dataset.destination,destination_path:link.pathname})})});
  ['playTop','playResult'].forEach(function(id){document.getElementById(id).addEventListener('click',function(){track('coach_2048_play_click',{destination_type:id==='playTop'?'top':'result',destination_path:'/puzzle-2048/'})})});
  var ad=document.querySelector('[data-ad-surface=coach_2048_inline]'),adTracked=false;function adView(){if(adTracked)return;adTracked=true;track('coach_2048_ad_impression',{ad_surface:'coach_2048_inline'})}if(ad&&'IntersectionObserver'in window){var observer=new IntersectionObserver(function(entries){if(entries.some(function(entry){return entry.isIntersecting})){adView();observer.disconnect()}},{threshold:.3});observer.observe(ad)}else if(ad)adView();
  try{(window.adsbygoogle=window.adsbygoogle||[]).push({})}catch(e){}
  track('coach_2048_view',{has_saved_board:Array.isArray(session.board),analysis_count:session.count});
}());
